#cloud-config
runcmd:
  - |
    #!/bin/bash
    set -e

    # 0. Set up the logging directory
    mkdir /home/agent/logging

    # Save logs into the logging directory
    # FIXME: set up an ingestion rule to bring output into Azure Monitor
    exec > /home/agent/logging/cloud_init.log 2>&1

    # Azure VM startup script
    # This runs on first boot via cloud-init

    # Update the package index list
    sudo apt-get update

    # Upgrade existing packages to their latest versions
    sudo apt-get upgrade -y

    # Install Docker
    sudo apt install docker.io -y

    # Add agent user to docker group
    sudo usermod -aG docker agent

    # Enable and start Docker service
    sudo systemctl enable docker
    sudo systemctl start docker

    # Update sentinel file so that dependents know we're ready to go
    touch /home/agent/startup_complete

    echo "VM initialization complete!"
